name: Ci

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Lint Format
        run: pnpm lint:prettier

      - name: Check Types
        run: pnpm build --filter=./packages/*

      - name: Run ESLint
        run: pnpm lint --filter=./packages/*

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: Install Node.js
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Check
        run: pnpm build
